services:
  postgres:
    image: postgres:16
    container_name: postgres_persistent
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgresqluser
      POSTGRES_PASSWORD: postgressqlpass
      POSTGRES_DB: emi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
